name: 构建和部署npm项目
on: push

jobs:
  npm-build:
    name: 构建npm项目
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 登录Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: 构建Docker镜像
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: xiongmaotongxueya/vue-app:latest
